name: iOS Build and Export

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # macOS is required to run xcodebuild
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Install Certificates
        # You will need to add your P12 certificate and provisioning profile to GitHub Secrets
        uses: apple-actions/import-codesign-certs@v3
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}

      #- name: Install Provisioning Profiles
      #  uses: apple-actions/download-provisioning-profiles@v3
      #  with:
      #    bundle-id: 'com.im.dime' # Your main bundle ID
      #    profile-type: 'ios-app-adhoc'
      #    issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
      #    api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
      #    api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}

      - name: Install All Provisioning Profiles
        run: |
          # Create the directory
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          
          # Decode each profile into the folder
          echo "${{ secrets.PROVISIONING_PROFILE_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/app.mobileprovision
          echo "${{ secrets.PROVISIONING_PROFILE_INTENT_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/intent.mobileprovision
          echo "${{ secrets.PROVISIONING_PROFILE_WIDGET_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/widget.mobileprovision
          echo "${{ secrets.PROVISIONING_PROFILE_UI_BASE64 }}" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/ui.mobileprovision
          
          echo "Successfully installed 4 provisioning profiles."

      - name: Build Archive
        run: |
          xcodebuild -project ./app/dime.xcodeproj \
                     -scheme dime \
                     -configuration Release \
                     -archivePath ./app/build/dime.xcarchive \
                     CODE_SIGN_STYLE=Manual \
                     CODE_SIGN_IDENTITY="Apple Distribution" \
                     PROVISIONING_PROFILE_SPECIFIER="Dime App" \
                     archive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive \
                     -archivePath ./app/build/dime.xcarchive \
                     -exportPath ./app/build/DimeApp \
                     -exportOptionsPlist ./app/ExportOptions.plist \

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-ipa
          path: ./app/build/DimeApp/*.ipa
